LANGUAGES = {
    "en": {
        "name": "English 🇺🇸",
        "start": "👋 Welcome! I am your daily assistant bot.",
        "language_changed": "✅ Language updated!",
        "main_menu": "Choose an option:",
        "ask_ai": "🤖 Ask me anything:",
        "ask_shopping": "🛒 Please send your shopping list (one per line):",
        "shopping_time_choice": "When should I remind you?\nChoose Today or send a specific date & time.",
        "ask_shopping_time": "📅 Please send reminder date and time:",
        "shopping_saved_today": "✅ Shopping list saved! I will remind you today.",
        "shopping_saved_later": "✅ Shopping list saved! Reminder set for {remind}.",
        "no_shopping_history": "📭 No shopping history yet!",
        "no_tasks": "📭 You have no tasks yet.",
        "your_tasks": "📋 Your tasks:",
        "task_added": "✅ Task added!",
        "task_mark_done": "✔️ Task marked done!",
        "unknown_input": "⚠️ I didn't understand that. Use the menu below.",
    },
    "fa": {
        "name": "Persian 🇮🇷",
        "start": "👋 خوش آمدید! من دستیار روزانه شما هستم.",
        "language_changed": "✅ زبان تغییر یافت!",
        "main_menu": "یک گزینه انتخاب کنید:",
        "ask_ai": "🤖 هر چیزی بپرس:",
        "ask_shopping": "🛒 لطفاً لیست خرید خود را ارسال کنید (هر خط یک مورد):",
        "shopping_time_choice": "چه زمانی یادآوری کنم؟\nامروز یا تاریخ خاص؟",
        "ask_shopping_time": "📅 لطفاً تاریخ و زمان یادآوری را ارسال کنید:",
        "shopping_saved_today": "✅ لیست خرید ذخیره شد! امروز یادآوری خواهد شد.",
        "shopping_saved_later": "✅ لیست خرید ذخیره شد! یادآوری برای {remind}.",
        "no_shopping_history": "📭 هنوز سابقه خریدی ندارید!",
        "no_tasks": "📭 هنوز تسکی ثبت نکرده‌اید.",
        "your_tasks": "📋 تسک‌های شما:",
        "task_added": "✅ تسک افزوده شد!",
        "task_mark_done": "✔️ تسک به انجام رسیده!",
        "unknown_input": "⚠️ متوجه نشدم. از منو استفاده کنید.",
    },
    "es": {
        "name": "Español 🇪🇸",
        "start": "👋 ¡Bienvenido! Soy tu asistente diario.",
        "language_changed": "✅ ¡Idioma actualizado!",
        "main_menu": "Elige una opción:",
        "ask_ai": "🤖 Pregúntame lo que quieras:",
        "ask_shopping": "🛒 Por favor envía tu lista de compras (una por línea):",
        "shopping_time_choice": "¿Cuándo debo recordarte?\nHoy o envía una fecha y hora.",
        "ask_shopping_time": "📅 Envía la fecha y hora de recordatorio:",
        "shopping_saved_today": "✅ ¡Lista de compras guardada! Te lo recordaré hoy.",
        "shopping_saved_later": "✅ ¡Lista guardada! Recordatorio para {remind}.",
        "no_shopping_history": "📭 ¡No hay historial de compras!",
        "no_tasks": "📭 Aún no tienes tareas.",
        "your_tasks": "📋 Tus tareas:",
        "task_added": "✅ ¡Tarea agregada!",
        "task_mark_done": "✔️ ¡Tarea completada!",
        "unknown_input": "⚠️ No entendí eso. Usa el menú abajo.",
    },
    "fr": {
        "name": "Français 🇫🇷",
        "start": "👋 Bienvenue! Je suis votre assistant quotidien.",
        "language_changed": "✅ Langue mise à jour!",
        "main_menu": "Choisissez une option:",
        "ask_ai": "🤖 Pose-moi une question:",
        "ask_shopping": "🛒 Envoie ta liste de courses (une par ligne):",
        "shopping_time_choice": "Quand dois-je te le rappeler?\nAujourd'hui ou envoie date et heure.",
        "ask_shopping_time": "📅 Envoie la date et heure de rappel:",
        "shopping_saved_today": "✅ Liste enregistrée! Je te le rappellerai aujourd'hui.",
        "shopping_saved_later": "✅ Liste enregistrée! Rappel pour {remind}.",
        "no_shopping_history": "📭 Pas d'historique d'achats!",
        "no_tasks": "📭 Pas encore de tâches.",
        "your_tasks": "📋 Vos tâches:",
        "task_added": "✅ Tâche ajoutée!",
        "task_mark_done": "✔️ Tâche complétée!",
        "unknown_input": "⚠️ Je n'ai pas compris. Utilise le menu.",
    },
    "de": {
        "name": "Deutsch 🇩🇪",
        "start": "👋 Willkommen! Ich bin dein täglicher Assistent.",
        "language_changed": "✅ Sprache aktualisiert!",
        "main_menu": "Wähle eine Option:",
        "ask_ai": "🤖 Frag mich etwas:",
        "ask_shopping": "🛒 Bitte sende deine Einkaufsliste (eine pro Zeile):",
        "shopping_time_choice": "Wann soll ich dich erinnern?\nHeute oder Datum & Uhrzeit senden.",
        "ask_shopping_time": "📅 Sende Datum & Uhrzeit für Erinnerung:",
        "shopping_saved_today": "✅ Einkaufsliste gespeichert! Ich erinnere dich heute.",
        "shopping_saved_later": "✅ Liste gespeichert! Erinnerung für {remind}.",
        "no_shopping_history": "📭 Keine Einkaufshistorie!",
        "no_tasks": "📭 Du hast noch keine Aufgaben.",
        "your_tasks": "📋 Deine Aufgaben:",
        "task_added": "✅ Aufgabe hinzugefügt!",
        "task_mark_done": "✔️ Aufgabe erledigt!",
        "unknown_input": "⚠️ Das habe ich nicht verstanden. Nutze das Menü.",
    },
    "tr": {
        "name": "Türkçe 🇹🇷",
        "start": "👋 Hoşgeldiniz! Günlük asistanınızım.",
        "language_changed": "✅ Dil güncellendi!",
        "main_menu": "Bir seçenek seçin:",
        "ask_ai": "🤖 Bir şey sor:",
        "ask_shopping": "🛒 Lütfen alışveriş listenizi gönderin (her satır bir madde):",
        "shopping_time_choice": "Ne zaman hatırlatayım?\nBugün veya tarih & saat gönderin.",
        "ask_shopping_time": "📅 Hatırlatma tarih ve saatini gönderin:",
        "shopping_saved_today": "✅ Alışveriş listesi kayıt edildi! Bugün hatırlatacağım.",
        "shopping_saved_later": "✅ Liste kayıt edildi! Hatırlatma {remind}.",
        "no_shopping_history": "📭 Alışveriş geçmişi yok!",
        "no_tasks": "📭 Henüz görev yok.",
        "your_tasks": "📋 Görevlerin:",
        "task_added": "✅ Görev eklendi!",
        "task_mark_done": "✔️ Görev tamamlandı!",
        "unknown_input": "⚠️ Anlamadım. Menüden seçenek seçin.",
    },
    "ar": {
        "name": "العربية 🇸🇦",
        "start": "👋 مرحباً! أنا مساعدك اليومي.",
        "language_changed": "✅ تم تغيير اللغة!",
        "main_menu": "اختر خياراً:",
        "ask_ai": "🤖 اسأل أي شيء:",
        "ask_shopping": "🛒 رجاءً أرسل قائمة التسوق (في كل سطر عنصر):",
        "shopping_time_choice": "متى أذكرك؟\nاليوم أو أرسل تاريخاً ووقتاً.",
        "ask_shopping_time": "📅 رجاءً أرسل تاريخ ووقت التذكير:",
        "shopping_saved_today": "✅ تم حفظ قائمة التسوق! سأذكرك اليوم.",
        "shopping_saved_later": "✅ تم حفظ القائمة! التذكير في {remind}.",
        "no_shopping_history": "📭 لا يوجد محفوظات تسوق!",
        "no_tasks": "📭 لا توجد مهام حتى الآن.",
        "your_tasks": "📋 مهامك:",
        "task_added": "✅ تم إضافة المهمة!",
        "task_mark_done": "✔️ تم إكمال المهمة!",
        "unknown_input": "⚠️ لم أفهم. استخدم القائمة.",
    },
}
