LANGUAGES = {
    "en": {"name": "English 🇺🇸", "welcome": "👋 Welcome!", "menu": "Choose an option 👇"},
    "fa": {"name": "فارسی 🇮🇷", "welcome": "👋 خوش آمدی!", "menu": "یک گزینه انتخاب کن 👇"},
    "es": {"name": "Español 🇪🇸", "welcome": "👋 ¡Bienvenido!", "menu": "Elige 👇"},
    "fr": {"name": "Français 🇫🇷", "welcome": "👋 Bienvenue!", "menu": "Choisissez 👇"},
    "de": {"name": "Deutsch 🇩🇪", "welcome": "👋 Willkommen!", "menu": "Wähle 👇"},
    "ru": {"name": "Русский 🇷🇺", "welcome": "👋 Добро пожаловать!", "menu": "Выберите 👇"},
    "tr": {"name": "Türkçe 🇹🇷", "welcome": "👋 Hoş geldin!", "menu": "Seç 👇"},
    "ar": {"name": "العربية 🇸🇦", "welcome": "👋 مرحبا!", "menu": "اختر 👇"},
    "it": {"name": "Italiano 🇮🇹", "welcome": "👋 Benvenuto!", "menu": "Scegli 👇"},
    "pt": {"name": "Português 🇵🇹", "welcome": "👋 Bem-vindo!", "menu": "Escolha 👇"},
    "hi": {"name": "Hindi 🇮🇳", "welcome": "👋 स्वागत है!", "menu": "चुनें 👇"},
    "zh": {"name": "中文 🇨🇳", "welcome": "👋 欢迎!", "menu": "请选择 👇"},
    "ja": {"name": "日本語 🇯🇵", "welcome": "👋 ようこそ!", "menu": "選択してください 👇"},
    "ko": {"name": "한국어 🇰🇷", "welcome": "👋 환영합니다!", "menu": "선택 👇"},
}
